### ISSUE TITLE
Team 18 SRS Review: Unclear which template is used

### ISSUE THREAD

**Issue by charlottechengg** [kelhuynh/OpenASL#6]
It is unclear which template is used, SRS did not reference the template, and sections added to the template are not identified.

**Comment by charlottechengg** [comment]
@kelhuynh Can you please create a label on your github for our review issues? It should say "Review-SRS-Team18", we don't have permissions.

**Comment by kelhuynh** [comment]
I was unable to add a label to my issue when reviewing another team. But I will manually add the label to each issue now

**Comment by charlottechengg** [comment]
That's ok, thank you so much!
